# Generated by Django 4.1.1 on 2022-10-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default=models.CharField(max_length=255), help_text='The topics that are discussed in the post', max_length=10),
        ),
    ]
