# Generated by Django 4.1.1 on 2022-10-25 04:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Birds', 'Birds'), ('RapMusic', 'Rap Music'), ('Games', 'Games'), ('Nonsense', 'Nonsense')], max_length=100),
        ),
    ]
