# Generated by Django 4.1.1 on 2022-10-21 19:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('birds', 'Birds'), ('rap music', 'Rap Music'), ('games', 'Games'), ('nonsense', 'Nonsense')], help_text='The topics that are discussed in the post', max_length=10, null=True), size=None),
        ),
    ]
