# Generated by Django 4.1.1 on 2022-10-25 04:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Birds', 'Birds'), ('RapMusic', 'Rap Music'), ('Games', 'Games'), ('Nonsense', 'Nonsense')], max_length=255),
        ),
    ]
