# Generated by Django 4.1.1 on 2022-10-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('birds', 'Birds'), ('rap music', 'Rap Music'), ('games', 'Games'), ('nonsense', 'Nonsense')], default=models.CharField(max_length=255), help_text='The topics that are discussed in the post', max_length=10),
        ),
    ]
